layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    - "Nand-2-Tetris-Part-II"
    - "ar-seven"
    - "ARM-challenges-and-writeups-for-ctf"
  
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: arseven
  instagram: raravind7
  # keybase: your_username
  linkedin: r-aravind-b5515b230
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  telegram: liverpoolgerrardsteve
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Flutter
    web_url: https://flutter.dev/
    image_url: https://i.pinimg.com/564x/f9/90/59/f99059c9960fb3a114dadf078146127c.jpg

  - name: Javascript
    web_url: https://www.javascript.com/
    image_url: https://i.pinimg.com/564x/0c/de/d3/0cded3a3276425911d55a2552bf361bf.jpg

  - name: Django
    web_url: https://www.djangoproject.com/
    image_url: https://avatars.githubusercontent.com/u/27804?s=200&v=4
